export const report = {
    report_title: 'Recuadacion por Canales',
    subtitle: 'Todos los canales del peaje La Chinita, Estado Zulia',
    created_on: '21/04/2022 10:05',
    requested_by: 'VC Pirela',
    col_titles: [
        {Header: 'Fecha', accessor: 'fecha', fexed: true},
        {Header: 'Estado', accessor: 'estado'},
        {Header: 'Peaje', accessor: 'peaje'},
        {Header: 'Canal', accessor: 'canal'},
        {Header: 'Categoria', accessor: 'categoria'},
        {Header: 'Medio', accessor: 'medio'},
        {Header: 'Recaudacion', accessor: 'reacudacion'},
    ],
    data: [
        {
            row: [
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '100',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '150',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '250',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '50',
                },
            ],
            summary: {
                fecha: '21/04/2022',
                subtotal: '550',
            },
        },
        {
            row: [
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '50',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '75',
                },
                {
                    fecha: '22/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '75',
                },
                {
                    fecha: '22/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '10',
                },
            ],
            summary: {
                fecha: '22/04/2022',
                subtotal: '210',
            },
        },
        {
            row: [
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '100',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '150',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '250',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '50',
                },
            ],
            summary: {
                fecha: '21/04/2022',
                subtotal: '550',
            },
        },
        {
            row: [
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '50',
                },
                {
                    fecha: '21/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #1',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '75',
                },
                {
                    fecha: '22/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Efectivo',
                    reacudacion: '75',
                },
                {
                    fecha: '22/04/2022',
                    estado: 'Zulia',
                    peaje: 'La Chinita',
                    canal: 'Canal #2',
                    categoria: 'Vehiculo Ligero',
                    medio: 'Debito',
                    reacudacion: '10',
                },
            ],
            summary: {
                fecha: '22/04/2022',
                subtotal: '210',
            },
        },
    ],
    summary: {
        total: '760',
    },
}
